### PR TITLE
File restructure clean up

### PR DESCRIPTION
**Pull request by gtangelo**
**Changes made:**
General cleanup of file structure to follow React convention. Some changes include the following:
- React component folders are capitalised first. i.e. `MyComponent` over `myComponent`
- Distinct react components now have its own folder (i.e. `index.less` containing that component less stylings, `index.jsx` containg the default export of the component and `MyComponent.jsx` containing the react logic for that component, all encapsulated in a `MyComponent` folder.)
- Removed some files that was not being used.

Current directory tree looks like this. Hopefully this will make orgainising components and general maintainace of the FE repo much better. **NOTE: ProgressionChecker and DegreeWizard are yet cleaned up - will be making another PR for those.**
```
.
├── App.jsx
├── App.less
├── assets
│   ├── circlesLogo.svg
│   ├── circlesWithBg.svg
│   ├── circlesWithRectBg.svg
│   ├── helpGifs
│   │   ├── additional-options.gif
│   │   ├── additional-options.png
│   │   ├── drag-and-drop.gif
│   │   ├── drag-and-drop.png
│   │   ├── hide-year.gif
│   │   ├── hide-year.png
│   │   ├── unschedule.gif
│   │   └── unschedule.png
│   ├── infographic.png
│   ├── infographic.svg
│   ├── infographicFontIndependent.svg
│   └── notAllowed.ico
├── axios.js
├── components
│   ├── Collapsible
│   │   ├── Collapsible.jsx
│   │   ├── index.jsx
│   │   └── index.less
│   ├── CourseTag
│   │   ├── CourseTag.jsx
│   │   ├── index.jsx
│   │   └── index.less
│   ├── FeedbackButton
│   │   ├── FeedbackButton.jsx
│   │   ├── index.jsx
│   │   └── index.less
│   ├── Header
│   │   ├── DrawerContent.jsx
│   │   ├── Header.jsx
│   │   ├── index.jsx
│   │   └── index.less
│   ├── LiquidProgressChart
│   │   ├── LiquidProgressChart.jsx
│   │   └── index.jsx
│   ├── PageLoading
│   │   ├── PageLoading.jsx
│   │   ├── index.jsx
│   │   └── index.less
│   ├── PageTemplate
│   │   ├── PageTemplate.jsx
│   │   └── index.jsx
│   ├── PlannerCart
│   │   ├── CartCourseCard.jsx
│   │   ├── PlannerCart.jsx
│   │   ├── index.jsx
│   │   └── index.less
│   ├── RadialBarChart
│   │   ├── RadialBarChart.jsx
│   │   ├── index.jsx
│   │   └── radialChartData.js
│   └── ThemeToggle
│       ├── ThemeToggle.jsx
│       └── index.jsx
├── constants.js
├── hooks
│   ├── useIntersectionObserver.js
│   └── useMediaQuery.js
├── index.js
├── pages
│   ├── CourseSelector
│   │   ├── CourseDescription
│   │   │   ├── AddToPlannerButton.jsx
│   │   │   ├── CourseAttribute.jsx
│   │   │   ├── CourseDescription.jsx
│   │   │   ├── LoadingSkeleton
│   │   │   │   ├── LoadingSkeleton.jsx
│   │   │   │   ├── index.jsx
│   │   │   │   └── index.less
│   │   │   ├── index.jsx
│   │   │   └── index.less
│   │   ├── CourseMenu
│   │   │   ├── CourseMenu.jsx
│   │   │   ├── LoadingSkeleton.jsx
│   │   │   ├── index.jsx
│   │   │   └── index.less
│   │   ├── CourseSearchBar
│   │   │   ├── CourseSearchBar.jsx
│   │   │   └── index.jsx
│   │   ├── CourseSelector.jsx
│   │   ├── CourseTabs
│   │   │   ├── CourseTab.jsx
│   │   │   ├── CourseTabs.jsx
│   │   │   ├── index.jsx
│   │   │   └── index.less
│   │   ├── index.jsx
│   │   ├── index.less
│   │   └── utils.js
│   ├── DegreeWizard
│   │   ├── DegreeWizard.jsx
│   │   ├── index.jsx
│   │   ├── index.less
│   │   └── steps
│   │       ├── DegreeStep.jsx
│   │       ├── MinorStep.jsx
│   │       ├── SpecialisationStep.jsx
│   │       ├── StartBrowsingStep.jsx
│   │       ├── YearStep.jsx
│   │       ├── spring.js
│   │       └── steps.less
│   ├── ProgressionChecker
│   │   ├── CourseComponents.jsx
│   │   ├── Dashboard.jsx
│   │   ├── DegreeCard.jsx
│   │   ├── ListView.jsx
│   │   ├── ListView2.jsx
│   │   ├── ListView3.jsx
│   │   ├── SkeletonCard.jsx
│   │   ├── SkeletonDashboard.jsx
│   │   ├── TableView.jsx
│   │   ├── main.jsx
│   │   └── main.less
│   └── TermPlanner
│       ├── ContextMenu
│       │   ├── ContextMenu.jsx
│       │   ├── index.jsx
│       │   └── index.less
│       ├── DraggableCourse
│       │   ├── DraggableCourse.jsx
│       │   ├── index.jsx
│       │   └── index.less
│       ├── HideYearTooltip
│       │   ├── HideYearTooltip.jsx
│       │   ├── index.jsx
│       │   └── index.less
│       ├── LoadingSkeleton
│       │   ├── LoadingSkeleton.jsx
│       │   └── index.jsx
│       ├── OptionsHeader
│       │   ├── HelpMenu.jsx
│       │   ├── OptionsHeader.jsx
│       │   ├── SaveMenu.jsx
│       │   ├── SettingsMenu.jsx
│       │   ├── index.jsx
│       │   └── index.less
│       ├── TermBox
│       │   ├── TermBox.jsx
│       │   ├── index.jsx
│       │   └── index.less
│       ├── TermPlanner.jsx
│       ├── UnplannedColumn
│       │   ├── UnplannedColumn.jsx
│       │   ├── index.jsx
│       │   └── index.less
│       ├── index.jsx
│       ├── index.less
│       └── validateTermPlanner.js
├── reducers
│   ├── courseTabsSlice.js
│   ├── coursesSlice.js
│   ├── degreeSlice.js
│   ├── plannerSlice.js
│   └── themeSlice.js
└── store.js
```

### CODE REVIEW

**Comment by Peedee2002** [comment]
@imagine-hussain 👀

**Comment by imagine-hussain** [comment]
> @imagine-hussain 👀


oh my, this is pretty big; I'll look at it after my exam tommorow

**Review by Peedee2002 — APPROVED** [review]
Lgtm, I'm interested in the stub files tho. Is there a reason for them?

**Comment by gtangelo** [comment]
Oh what stub files were you referring to 😅? @Peedee2002

**Review by imagine-hussain — APPROVED** [review]
New file structure looks really nice. Great work!

**Review by imagine-hussain — COMMENTED** [review]
New file structure looks really clean, great work!

**Pull request merged**
