### PR TITLE
feat(frontend) fuzzy-find-degree-wizard

### PR DESCRIPTION
**Pull request by imagine-hussain**
- in setup, degree is now fuzzily searched
- no longer need to type *exact* degree
- fuzz is weighted by what's effectively a normalised version of levenstein distance
- in cases of equal weighting (usualyl when both have a weight of 1), uses string len as tie breaker
- only gives user the 8 most relevant results

image

### CODE REVIEW

**Comment by Peedee2002** [comment]
I think this one is easy to merge, you should delete the failing frontend test tho

**Comment by imagine-hussain** [comment]
Deleted the failing test for not being relevant anymore.

**Review by Peedee2002 — APPROVED** [review]

**Comment by ollibowers** [comment]
looks good but am withholding review/merge until 331 gets merged

**Comment by imagine-hussain** [comment]
That's reasonable. Look forward to it :)

**Comment by imagine-hussain** [comment]
Closing. We will properly target 331 with #1133 as this was brought up to date with dev, making it harder to change base to `331-staging`

**Pull request closed without merging**
