### PR TITLE
Tests/circles 320 evaluate cores token

### PR DESCRIPTION
**Pull request by imagine-hussain**
tests for `User.has_taken` to ensure correctness for the the new marks-compatible paradigm

Thoughts:
- Many of these would be very ripe for property based testing (if that's something we're moving to eventually - i remember james saying we have a preference for it); This would however required tests to get access to the course list

### CODE REVIEW

**Comment by Peedee2002** [comment]
Yes, I love property based testing. I don't think it requires access to the course list either (make up marks for fake courses for example)

**Comment by imagine-hussain** [comment]
> Yes, I love property based testing. I don't think it requires access to the course list either (make up marks for fake courses for example)

We should make a card for converting tests to be property based.

**Comment by imagine-hussain** [comment]
> > Yes, I love property based testing. I don't think it requires access to the course list either (make up marks for fake courses for example)
> 
> We should make a card for converting tests to be property based.

also, now that I think about it, you're right, we can use any made-up courses we like

**Comment by imagine-hussain** [comment]
Also, for some reason CI isn't re-running so, proof of pass
image

**Comment by ollibowers** [comment]
looks insanely good to me!

**Review by ollibowers — APPROVED** [review]

**Review by joooooooooooooooooooooooooooooooooooosh — APPROVED** [review]

**Pull request merged**
