### PR TITLE
Added disclaimer that only cs degree is supported

### PR DESCRIPTION
**Pull request by Uzaif-Sheikh**

### CODE REVIEW

**Review by Peedee2002 — APPROVED** [review]
nice

**Review by gtangelo — APPROVED** [review]
Could you attach a picture showcasing what the disclaimer would look like on the UI? Thanks 😄

**Comment by gtangelo** [comment]
Other than that, everything looks good besides the merge conflict apparently.

**Comment by Peedee2002** [comment]
@Uzaif-Sheikh bump

**Comment by Uzaif-Sheikh** [comment]
> Could you attach a picture showcasing what the disclaimer would look like on the UI? Thanks 😄

CF-161-Screenshot 2022-04-19 142304

**Comment by gtangelo** [comment]
lgtm! @Uzaif-Sheikh just resolve the merge coflicts before merging :)

**Pull request merged**
