### PR TITLE
chore: update CODEOWNERS for 2024 devsoc

### PR DESCRIPTION
**Pull request by ollibowers**
🥺  would like platform approval before merge

### CODE REVIEW

**Comment by lhjt** [comment]
I think you should have the github circles team owner role rather than hardcoding you and martin to be the codeowners so we don't have to change this every year 👍

**Review by lhjt — CHANGES_REQUESTED** [review]
Change this to reference your team handle instead of referencing you both directly

**Comment by ollibowers** [comment]
> Change this to reference your team handle instead of referencing you both directly

Would you want the platform codeowners to just be platform leads as well? @lhjt

**Comment by lhjt** [comment]
> > Change this to reference your team handle instead of referencing you both directly
> 
> Would you want the platform codeowners to just be platform leads as well? @lhjt

Oh I think just platform is actually fine since the team will need to be making changes as a whole 👍

**Comment by ollibowers** [comment]
> > > Change this to reference your team handle instead of referencing you both directly
> > 
> > 
> > Would you want the platform codeowners to just be platform leads as well? @lhjt
> 
> Oh I think just platform is actually fine since the team will need to be making changes as a whole 👍

awesome, am good to go then

**Review by lhjt — APPROVED** [review]

**Pull request merged**
