### PR TITLE
Added ReactTooltip when isSmall == true

### PR DESCRIPTION
**Pull request by Uzaif-Sheikh**
Created a reactTooltip when the course is small:

ezgif com-gif-maker

### CODE REVIEW

**Review by gtangelo — APPROVED** [review]
Lgtm!

**Review by Peedee2002 — APPROVED** [review]
pretty

**Comment by hdphuong** [comment]
How does this look when there is warning/alert?

**Comment by Uzaif-Sheikh** [comment]
> How does this look when there is warning/alert?

ezgif com-gif-maker (1)

**Comment by hdphuong** [comment]
Lit 🔥

**Pull request merged**
