### PR TITLE
feat(BE/FE): replace updateStartYear reducer with API [CF-413]

### PR DESCRIPTION
**Pull request by lhvy**
- Replaces the updateStartYear degreePlanner slice with the according backend API call.
- Updates the logic of updating a start year; now changing the start year will move all planned items to the correct relative year. (i.e. courses planned in 2025 will go to 2024 if the start year is shifted back by one)

### CODE REVIEW

**Review by imagine-hussain — APPROVED** [review]
BE lgtm

**Comment by imagine-hussain** [comment]
syncing with the #987 branch may fix the failing pipelines. Otherwise, looks like this is coming along nicely

**Comment by lhvy** [comment]
> syncing with the https://github.com/csesoc/circles/pull/987 branch may fix the failing pipelines. Otherwise, looks like this is coming along nicely

Seems to have fixed BE tests, I'll need to make changes similar to #1038 to make FE pass.

**Comment by imagine-hussain** [comment]
> > syncing with the #987 branch may fix the failing pipelines. Otherwise, looks like this is coming along nicely
> 
> Seems to have fixed BE tests, I'll need to make changes similar to #1038 to make FE pass.

Looks good!!! Feel free to merge this in as is. Then you can get started w/ the respective react-query stuff.
Great work!

**Review by imagine-hussain — APPROVED** [review]

**Comment by lhvy** [comment]
> > > syncing with the #987 branch may fix the failing pipelines. Otherwise, looks like this is coming along nicely
> > 
> > 
> > Seems to have fixed BE tests, I'll need to make changes similar to #1038 to make FE pass.
> 
> Looks good!!! Feel free to merge this in as is. Then you can get started w/ the respective react-query stuff. Great work!

Alright, sounds good. I'll merge in now, just fixed conflicts.

**Pull request merged**
