### PR TITLE
fix: menu on navbar

### PR DESCRIPTION
**Pull request by ollibowers**
subpage menu now should use entire width given in navbar. also made sure the logo gets squished regardless of how many buttons we may add. 

<3

### CODE REVIEW

**Comment by Peedee2002** [comment]
Pics?

**Comment by imagine-hussain** [comment]
Fixes #965

**Comment by ollibowers** [comment]
> Pics?

picture of it working
image

picture of the menu getting full width
image

picture of @Peedee2002 
image

**Review by leonardo-fan — APPROVED** [review]
looks great to me, big props for picking this up!

**Pull request merged**
