### PR TITLE
chore(ci): add test reporting to ci

### PR DESCRIPTION
**Pull request by lhjt**
This PR adds the test result comment for all PRs.

### CODE REVIEW

**Comment by Peedee2002** [comment]
what does this do 👀

**Comment by lhjt** [comment]
> what does this do 👀

Once/If I get it to work, you'll see 😎

**Comment by Peedee2002** [comment]
Yo @lhjt there is a way to exclude files from coverage right?

**Comment by lhjt** [comment]
> Yo @lhjt there is a way to exclude files from coverage right?

Yes, [there is](https://pytest-cov.readthedocs.io/en/latest/config.html?highlight=exclude#:~:text=using%20a%20.coveragerc%20file%20with%20the%20omit%20option%20set). Feel free to add in a `.coveragerc` file to this branch and push it and we can check it out.

**Comment by lhjt** [comment]
I'm unsatisfied with the format that the code coverage PR comment uses so I have removed it for the time being. Otherwise this is ready for review.

**Review by Peedee2002 — APPROVED** [review]
Very cool

**Pull request merged**
