### PR TITLE
fix(backend) Update Python deps and Docker Compose

### PR DESCRIPTION
**Pull request by lhvy**
Running the latest versions of Python and Docker causes issues. The following changes should fix this, and I believe they are still backwards-compatible enough™️ for our production environment.

- Python deps updated to fix installs on Apple Silicon/latest macOS
- Raw string used in a number of places to fix runtime issues (regex) or linter problems (docstrings)
- Docker Compose version field removed (it was already deprecated, but latest Docker Compose no longer supports it)
- Docker Compose containers renamed so no clashes (throws errors on latest Docker Compose, even if containers with the same name never run at simultaneously

### CODE REVIEW

**Comment by lhvy** [comment]
It is **not** good that I re-ran CI and it passed this time. To be clear, I don't think I broke anything, but I don't know why it failed once...

**Review by martanman — APPROVED** [review]
lgtm

**Comment by lhvy** [comment]
Removed any changes in `package-lock.json` to avoid conflicts with `bring-to-dev`

**Review by ollibowers — APPROVED** [review]
lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm lgtm

**Pull request merged**
